### ISSUE TITLE
Cannot install on Python3

### ISSUE THREAD

**Issue by kostiantynvoiku** [s4int/robotframework-BrowserMobProxyLibrary#6]
```
% python -V
Python 3.7.0

% pip install robotframework-browsermobproxylibrary
Collecting robotframework-browsermobproxylibrary
  Using cached https://files.pythonhosted.org/packages/5b/1e/37137c471119e1b4542bf6816e2136386aa7ce71875d6f810b46a968da71/robotframework-browsermobproxylibrary-0.1.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5y/24rf8x8j1kl_f9l3s1txlc8c0000gn/T/pip-install-dqnhvpri/robotframework-browsermobproxylibrary/setup.py'"'"'; __file__='"'"'/private/var/folders/5y/24rf8x8j1kl_f9l3s1txlc8c0000gn/T/pip-install-dqnhvpri/robotframework-browsermobproxylibrary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5y/24rf8x8j1kl_f9l3s1txlc8c0000gn/T/pip-install-dqnhvpri/robotframework-browsermobproxylibrary/pip-egg-info
         cwd: /private/var/folders/5y/24rf8x8j1kl_f9l3s1txlc8c0000gn/T/pip-install-dqnhvpri/robotframework-browsermobproxylibrary/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5y/24rf8x8j1kl_f9l3s1txlc8c0000gn/T/pip-install-dqnhvpri/robotframework-browsermobproxylibrary/setup.py", line 9, in <module>
        execfile(join(dirname(__file__), 'src', 'BrowserMobProxyLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by phunguyen202** [comment]
Hello, any update on this. Maybe, the proxy will not be enhanced more?

**Comment by sparkymartin** [comment]
I, too, am looking for a Python 3 compatible version. Is anyone maintaining this?

**Comment by stdedos** [comment]
You may use my fork if you want https://github.com/stdedos/robotframework-BrowserMobProxyLibrary

I'll try to keep master stable-ish, but YMMV. Minimum changes in https://github.com/stdedos/robotframework-BrowserMobProxyLibrary/commit/fc6623c3d9970cbc5671aa4fea53a029e2809e74 commit

**Comment by s4int** [comment]
Hi, sorry for very late respone. I've just published new version with fixed install for python3.
As a bonus you can find travis-ci integration with basic tests.

Those tests are also a good example of how to use it with docker and selenium-hub
